## 1.多特征与向量化 16-18

### 1.1 这一节要解决什么问题？

之前我们预测房价时，只用了一个输入特征：
- 房子面积

但是实际预测房价时，可能需要多个特征，例如：
- 房子面积
- 卧室数量
- 楼层数量
- 房龄

所以这一节要解决的问题是：**如何用多个输入特征一起预测房价？**

### 1.2 核心公式 / 核心概念

一个训练样本不再只是一个数字 $x$，而是一组特征：$\vec{x} = [x_1, x_2, x_3, ..., x_n]$

每一个特征都有对应的参数：$\vec{w} = [w_1, w_2, w_3, ..., w_n]$

多变量线性回归模型是：

$f_{\vec{w},b}(\vec{x}) = w_1x_1 + w_2x_2 + \cdots + w_nx_n + b$

也可以写成：

$f_{\vec{w},b}(\vec{x}) = \vec{w} \cdot \vec{x} + b$



### 1.3 这节我需要记住什么？

- 一个样本可以有多个特征
- 每个特征都有一个对应的参数 $w$
- 多变量线性回归本质上还是线性回归
- 输入从一个数字变成了一个向量
- 参数 $w$ 也从一个数字变成了一个向量

最核心：**多特征就是用多个输入信息一起预测结果。**

### 1.4 和前面内容的关系

C1-W1 是一元线性回归：$f_{w,b}(x)=wx+b$,只有一个特征 $x$。

C1-W2 是多变量线性回归：$f_{\vec{w},b}(\vec{x})=\vec{w}\cdot\vec{x}+b$,有多个特征 $x_1,x_2,...,x_n$。

可以理解成：**C1-W2 是 C1-W1 的扩展版，把一个输入扩展成多个输入。**

--------

## 2. 向量化 Vectorization

### 2.1这一节要解决什么问题？

多变量线性回归中，特征变多了。

如果有很多特征，用普通写法会很麻烦：

$$
w_1x_1+w_2x_2+w_3x_3+\cdots+w_nx_n+b
$$

所以这一节要解决的问题是：

> 如何用更简洁、更高效的方式计算多变量线性回归模型？

答案就是：

> 向量化 Vectorization

---

### 2.2核心公式 / 核心概念

多变量模型：

$$
f_{\vec{w},b}(\vec{x})=w_1x_1+w_2x_2+\cdots+w_nx_n+b
$$

向量化写法：

$$
f_{\vec{w},b}(\vec{x})=\vec{w}\cdot\vec{x}+b
$$

在 Python 里通常写成：

`np.dot(w, x) + b`

其中：

- `w` 是参数向量
- `x` 是特征向量
- `np.dot(w, x)` 表示点积
- 点积就是对应位置相乘再相加

例如：

$$
\vec{w}\cdot\vec{x}=w_1x_1+w_2x_2+w_3x_3
$$

---

### 2.3这节我需要记住什么？

- 向量化可以替代手写很多项相加
- `np.dot(w, x)` 就是点积
- 点积表示对应位置相乘再相加
- 向量化代码更简洁
- 向量化计算速度更快

最核心：

> `np.dot(w, x) + b` 就是多变量线性回归模型的代码写法。

---

### 2.4和前面内容的关系

C1-W1 中，一个特征时：

`f_wb = w * x + b`

C1-W2 中，多个特征时：

`f_wb = np.dot(w, x) + b`

可以理解成：

> `np.dot(w, x)` 是把多个 `w * x` 一次性算完。

## 3. 代码如下：

In [6]:
import numpy as np
import time

"""
1,向量创建
"""
#创建向量
a = np.zeros(4); #创建一维的4个0元素
print(f"np.zeros(4): a={a},  a_shape={a.shape}, a_data_type={a.dtype}")

#创建随机向量，0-1之间的小树
a = np.random.random_sample(4); 
print(f"随即向量:a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4): a=[0. 0. 0. 0.],  a_shape=(4,), a_data_type=float64
随即向量:a = [0.97252221 0.7895086  0.79596945 0.90561837], a shape = (4,), a data type = float64


In [7]:
#使用 np.arange() 创建连续数字
a = np.arange(4.)
print(f"结果: a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

结果: a = [0. 1. 2. 3.], a shape = (4,), a data type = float64


In [13]:
#手动指定数值创建向量
a = np.array([5, 4, 3, 2]) #整数
b = np.array([5.0,1.5,2.3,6.4]) #浮点数
print(a,b)
print(a.shape,b.shape)
print(a.dtype,b.dtype)

[5 4 3 2] [5.  1.5 2.3 6.4]
(4,) (4,)
int64 float64


In [34]:
"""
2,向量操作
"""

#2.1索引
a = np.arange(10)
print(a)
print(a[2]) #从0开始数
print(a[-1]) #最后一个元素

[0 1 2 3 4 5 6 7 8 9]
2
9


In [38]:
#2.2切片 都是 从0开始数，包前不包后
print(a)
print(a[2:7:1]) #从0开始数，包前2不包后7
print(a[2:7:2]) #中间间隔一个
print(a[3:]) #3以后的元素,包3
print(a[:3]) #3以前的，不包3
print(a[:])  #所有元素

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6]
[2 4 6]
[3 4 5 6 7 8 9]
[0 1 2]
[0 1 2 3 4 5 6 7 8 9]


In [44]:
#2.3单一向量操作

a = np.array([1,2,3,4])
print(a)
#a中每个元素为-
b = -a
print(b)
#a中所有元素想加
b = np.sum(a)
print(b)
#计算a的平均值
b = np.mean(a)
print(b)
#a的每个元素平方
b = a**2
print(b)

[1 2 3 4]
[-1 -2 -3 -4]
10
2.5
[ 1  4  9 16]


In [45]:
#2.4矢量(两个向量中各个元素做运算)操作,只能在同维度下操作
a = np.array([1,2,3,4])
b = np.array([-1,-2,3,4])
print(a+b)

[0 0 6 8]


In [46]:
#2.5标量(一个数和一个向量做运算)
a = np.array([1,2,3,4])
print(5*a)

[ 5 10 15 20]


In [47]:
#2.6点积(类似于：w1*b1 + w2*b2 +...)
a = np.array([1,2,3,4])
b = np.array([-1,4,3,2])
print(np.dot(a,b)) #np.dot(a,b),a向量与b向量点积


24


In [58]:
"""
3,矩阵创建
"""

#3.1矩阵创建
a = np.zeros((1,5)) #创建一个1行5列的0元素
print(a)
print(a.shape) #该向量为1行5列

b = np.zeros((2,3)) #创建一个2行3列的0元素
print(b)
print(b.shape)

[[0. 0. 0. 0. 0.]]
(1, 5)
[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [60]:
#手动制定数据
a = np.array([[2],[4],[5]]); 
print(a)
print(a.shape)

[[2]
 [4]
 [5]]
(3, 1)


In [84]:
"""
4,矩阵操作
"""
#4.1索引
a = np.arange(6).reshape(-1,2) #-1系统自动判断行，2为两列
print(a)
print(a.shape)

print(a[2,0]) #相当于平时的第3行，第1列的数字。

print(a[2])  #相当于平时第三行所有

[[0 1]
 [2 3]
 [4 5]]
(3, 2)
4
[4 5]


In [90]:
##4.2切片 (开始:停止:步骤)
a = np.arange(20).reshape(-1,10) #创建一个10列
print(a)
print(a.shape)
print(a[0,2:7:1]) #第一行的切片
print(a[:,2:7:1]) #所有行的切片
print(a[1,:])     #第二行的切片(:表示所有的数)
print(a[1])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
(2, 10)
[2 3 4 5 6]
[[ 2  3  4  5  6]
 [12 13 14 15 16]]
[10 11 12 13 14 15 16 17 18 19]
[10 11 12 13 14 15 16 17 18 19]
