In [2]:
import numpy as np

#创建整数数组
arr1 = np.array([1, 2, 3, 4])
print(arr1) 

#创建浮点数数组
arr2 = np.array([1.0, 2.0, 3.0, 4.0])
print(arr2) 

[1 2 3 4]
[1. 2. 3. 4.]


In [3]:
#给arr1插入浮点数,被截断，数组仍为整数
arr1[0] = 20.5
print(arr1) 

[20  2  3  4]


In [4]:
#整数数组转换为浮点数数组
arr1_float = arr1.astype(float)
print(arr1_float)

#浮点数数组转换为整数数组
arr2_int = arr2.astype(int)
print(arr2_int)

[20.  2.  3.  4.]
[1 2 3 4]


In [ ]:
#一维数组
a=np.array([1, 2, 3])
print(a)
print(a.ndim)  # 输出维度
print(a.shape)  # 输出形状
print(a.size)   # 输出元素数量

#二维数组（两个中括号）
b=np.array([[4, 5, 6]])
print(b)
print(b.ndim)  # 输出维度
print(b.shape)  # 输出形状,查看几行几列，这里是1行3列
print(b.size)   # 输出元素数量

[1 2 3]
1
(3,)
3
[[4 5 6]]
2
(1, 3)
3


In [9]:
#索引访问元素
print(a[0])  # 输出1

#赋值
a[0] = 10
print(a)  

#切片
print(a[1:3])  

10
[10  2  3]
[2 3]


In [15]:
#二维数组索引
c=np.array([[4, 5, 6],[7, 8, 9]])
print(c)  # 输出二维数组
print(c[0, 1])  # 逗号前面是行，逗号后面是列，输出5
print(c[1, 2])  
print(c[0, :])  # 输出第一行
print(c[:, 1])  # 输出第二列


[[4 5 6]
 [7 8 9]]
5
9
[4 5 6]
[5 8]


In [19]:
#创建基础数组
np.zeros(5)  # 创建一个包含5个元素的全零数组

array([0., 0., 0., 0., 0.])

In [20]:
np.ones(5)   # 创建一个包含5个元素的全一数组

array([1., 1., 1., 1., 1.])

In [22]:
np.arange(0, 10, 2)  # 创建一个从0到10（不包括10），步长为2的数组

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(0, 1, 5)  # 创建一个从0到1的等差数列(每两个数间距一样)，包含5个元素

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
np.ones(5, dtype=int)  # 创建一个包含5个元素的全一数组(整数类型)

array([1, 1, 1, 1, 1])

In [ ]:
#排序
arr = np.array([3, 1, 4, 1, 5])
a=np.sort(arr) #保存排序后的数组
a

array([1, 1, 3, 4, 5])